<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <LangVersion>8</LangVersion>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.12.1" />
      <PackageReference Include="JetBrains.Profiler.Api" Version="1.1.7" />
      <PackageReference Include="Gravy.ImmutableGeometry" Version="0.3.0-alpha" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\PathFinder\PathFinder.csproj" />
      <ProjectReference Include="..\SimpleWorld\SimpleWorld.csproj" />
    </ItemGroup>

</Project>
