name: Deploy API Documentation

on:
  push:
    branches: [ master ]

jobs:
  api-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore PathFinder && dotnet restore Extras/PathFinder.DocFx
      - name: Build
        run: dotnet build --no-restore Extras/PathFinder.DocFx
      - name: Deploy
        uses: maxheld83/ghpages@master
        env:
          BUILD_DIR: Extras/PathFinder.DocFx/_site/
          GH_PAT: ${{ secrets.GH_PAT }}
