name: Publish on NuGet
on:
  push:
    branches: [ master ]

jobs:
  nuget:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies (PathFinder)
        run: dotnet restore PathFinder
      - name: Build
        run: dotnet build --no-restore PathFinder
      - name: Publish on NuGet and Tag
        id: publish_nuget
        uses: Rebel028/publish-nuget@2.6.1
        with:
          PROJECT_FILE_PATH: PathFinder/PathFinder.csproj
          PACKAGE_NAME: PathFinder
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true