name: Publish on NuGet
on:
  push:
    branches: [ master ]

jobs:
  nuget:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Publish on NuGet and Tag
        id: publish_nuget
        uses: drusellers/publish-nuget@master
        with:
          PROJECT_FILE_PATH: PathFinder/PathFinder.csproj
          PACKAGE_NAME: Gravy.PathFinder
          VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true