name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies (PathFinder)
      run: dotnet restore PathFinder
    - name: Restore dependencies (PathFinderUnitTests)
      run: dotnet restore PathFinderUnitTests
    - name: Build
      run: dotnet build --no-restore PathFinderUnitTests
    - name: Test
      run: dotnet test --no-build --verbosity normal PathFinderUnitTests
